a = int(input('Digite um número:'))
b = int(input('Digite outro número:'))
soma = (a + b)
sub = a - b
prod = a * b
div = a / b
print(f'A soma entre {a} e {b} = {soma}' )
print(f'A subtração entre {a} e {b} = {sub}')
print(f'O produto entre {a} e {b} = {prod}')
print(f'A divisão entre {a} e {b} = {div}')
